// <auto-generated />
using System;
using M5Storage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace M5Storage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605185312_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("M5Storage.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ALERTA");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("Nivel")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NIVEL");

                    b.Property<int>("RecursoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RECURSO_ID");

                    b.Property<int>("Resolvido")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RESOLVIDO");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.ToTable("T_ALERTAS");
                });

            modelBuilder.Entity("M5Storage.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataMovimentacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_MOVIMENTACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DESCRICAO");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("QUANTIDADE");

                    b.Property<int>("RecursoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RECURSO_ID");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TIPO_MOVIMENTACAO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("T_MOVIMENTACOES");
                });

            modelBuilder.Entity("M5Storage.Models.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CATEGORIA");

                    b.Property<int>("Critico")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CRITICO");

                    b.Property<decimal>("Minimo")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("MINIMO");

                    b.Property<string>("Nivel")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NIVEL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("QUANTIDADE");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMA_ATUALIZACAO");

                    b.HasKey("Id");

                    b.ToTable("T_RECURSOS");
                });

            modelBuilder.Entity("M5Storage.Models.RecursoEnergia", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    b.Property<string>("TipoEnergia")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_ENERGIA");

                    b.HasKey("Id");

                    b.ToTable("T_RECURSO_ENERGIA");
                });

            modelBuilder.Entity("M5Storage.Models.RecursoMedicamento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("Validade")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("VALIDADE");

                    b.HasKey("Id");

                    b.ToTable("T_RECURSO_MEDICAMENTO");
                });

            modelBuilder.Entity("M5Storage.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("T_USUARIOS");
                });

            modelBuilder.Entity("M5Storage.Models.Alerta", b =>
                {
                    b.HasOne("M5Storage.Models.Recurso", "Recurso")
                        .WithMany("Alertas")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("M5Storage.Models.Movimentacao", b =>
                {
                    b.HasOne("M5Storage.Models.Recurso", "Recurso")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("M5Storage.Models.Usuario", "Usuario")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recurso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("M5Storage.Models.RecursoEnergia", b =>
                {
                    b.HasOne("M5Storage.Models.Recurso", "Recurso")
                        .WithOne("RecursoEnergia")
                        .HasForeignKey("M5Storage.Models.RecursoEnergia", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("M5Storage.Models.RecursoMedicamento", b =>
                {
                    b.HasOne("M5Storage.Models.Recurso", "Recurso")
                        .WithOne("RecursoMedicamento")
                        .HasForeignKey("M5Storage.Models.RecursoMedicamento", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("M5Storage.Models.Recurso", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Movimentacoes");

                    b.Navigation("RecursoEnergia");

                    b.Navigation("RecursoMedicamento");
                });

            modelBuilder.Entity("M5Storage.Models.Usuario", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
